### ISSUE TITLE
disabled the local database table ORM

### ISSUE THREAD

**Issue by Snowbaha** [Setono/SyliusPickupPointPlugin#51]
Hello,

Is it possible to not create the database `setono_sylius_pickup_point__pickup_point` with the configuration?
I tried something like:

```yaml
setono_sylius_pickup_point:
    local: false 
    providers:
        faker: true


```
but it is not working.
